AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Simple single host deployment that allows you to automatically scp

Parameters:

  VpcId:
    Description: VPC identifier
    Type: String
    Default: vpc-24t823984h02f2

  SubnetId:
    Description: Subnet identifier
    Type: String
    Default: subnet-24t823984h02f2

  KeyPair:
    Description: Key pair name
    Type: String
    Default: example.pem

  AMI:
    Description: Select the AMI ID that you want to use.
    Type: String
    Default: ami-0dc5e9ff792ec08e3


Resources:

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Traffic to & from hosts for RDP, VNC, and SSH
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5900
          ToPort: 5900
          CidrIp: 0.0.0.0/0

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        NetworkInterfaces:
          - DeviceIndex: 0
            Groups:
              - !Ref SecurityGroup
            DeleteOnTermination: true
        ImageId: !Ref AMI
        InstanceType: t3.micro
        KeyName: !Ref KeyPair
        UserData:
          Fn::Base64:
            Fn::Sub: |
              #!/bin/bash
              echo 'I am a start up script'

  AutoscalingGroup:
    DependsOn:
      - UbuntuLaunchTemplate
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MaxSize: 10
      MinSize: 1
      DesiredCapacity: 1
      VPCZoneIdentifier:
        - !Ref SubnetId
